In [2]:
# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

In [3]:
from keras.preprocessing import image
model = load_model('vgg16_fr.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


In [4]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\nilay\AppData\Local\Temp\ipykernel_16724\2630192672.py:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [7]:
# Doing some Face Recognition with the webcam
from datetime import datetime


video_capture = cv2.VideoCapture(0)
while True:
    _, image = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(image)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
        #Our keras model used a 4D tensor, (images x height x width x channel)
        #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.7):
            name='Barak'
        elif(pred[0][1]>0.7):
            name='Nilay'
        elif(pred[0][2]>0.7):
            name='Trevor'
            
        current_date = datetime.now()
        cv2.putText(image,name+str(current_date), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(image,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', image)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 204ms/step
[[6.5931961e-18 1.6781954e-08 1.0000000e+00]]
1/1 [==============================] - 0s 178ms/step
[[1.5523469e-17 1.2969223e-03 9.9870300e-01]]
1/1 [==============================] - 0s 186ms/step
[[7.0619135e-17 9.9997842e-01 2.1617676e-05]]
1/1 [==============================] - 0s 189ms/step
[[1.1069905e-25 9.9999988e-01 9.0359713e-08]]
1/1 [==============================] - 0s 194ms/step
[[6.128167e-16 4.862758e-07 9.999995e-01]]
1/1 [==============================] - 0s 190ms/step
[[5.799392e-19 9.999999e-01 8.166466e-08]]
1/1 [==============================] - 0s 180ms/step
[[1.4989994e-20 2.5620459e-10 1.0000000e+00]]
1/1 [==============================] - 0s 180ms/step
[[6.34136775e-17 1.00000000e+00 1.48811505e-08]]
1/1 [==============================] - 0s 178ms/step
[[4.1241263e-23 2.3094851e-03 9.9769056e-01]]
1/1 [==============================] - 0s 183ms/step
[[1.5528579e-14 9.8743266e-01 1.2567302e-02]]
1/1 [========